import { describe, expect, it } from "vitest";
import { buildDefault730Template } from "@/lib/domain/checklist-template";
import { assertSameOrganization, calculatePracticeProgress, countMissingRequiredItems, createPracticeFromTemplate, deriveSuggestedPracticeStatus } from "@/lib/domain/practice";
import type { Practice, PracticeItem } from "@/types/models";
function idFactory() { let counter = 0; return () => `id-${++counter}`; }
const now = () => "2026-01-01T00:00:00.000Z";
describe("730 checklist template", () => { it("seeds the default categories and items", () => { const seeded = buildDefault730Template(idFactory(), now); expect(seeded.template.key).toBe("modello-730-default"); expect(seeded.categories.map((c) => c.name)).toEqual(["Dati anagrafici", "Redditi", "Immobili", "Spese sanitarie", "Spese famiglia e istruzione", "Previdenza e assicurazioni", "Bonus e detrazioni", "Altro"]); expect(seeded.items).toHaveLength(29); expect(seeded.items.every((i) => i.required)).toBe(true); }); });
describe("practice creation", () => { it("creates practice items from the default template", () => { const createId = idFactory(); const seeded = buildDefault730Template(createId, now); const result = createPracticeFromTemplate({ organizationId: "org-1", clientId: "client-1", fiscalYear: 2025, template: seeded.template, categories: seeded.categories, templateItems: seeded.items, createId, now }); expect(result.practice.status).toBe("draft"); expect(result.practice.publicLinkEnabled).toBe(true); expect(result.practiceItems).toHaveLength(29); }); });
describe("practice progress", () => { it("counts approved and not_needed as complete", () => { const items = [item("approved"), item("not_needed"), item("requested"), item("uploaded"), item("needs_correction")]; expect(calculatePracticeProgress(items)).toBe(2 / 5); expect(countMissingRequiredItems(items)).toBe(3); }); it("returns zero with no required items", () => { expect(calculatePracticeProgress([item("approved", false)])).toBe(0); }); });
describe("practice status derivation", () => { it("keeps archived manual", () => expect(deriveSuggestedPracticeStatus(practice("archived"), [item("approved")])).toBe("archived")); it("suggests needs_review with uploaded item", () => expect(deriveSuggestedPracticeStatus(practice("sent"), [item("uploaded"), item("requested")])).toBe("needs_review")); it("suggests in_progress for touched non-uploaded", () => expect(deriveSuggestedPracticeStatus(practice("sent"), [item("approved"), item("requested")])).toBe("in_progress")); it("suggests complete when all required done", () => expect(deriveSuggestedPracticeStatus(practice("sent"), [item("approved"), item("not_needed")])).toBe("complete")); it("keeps sent when untouched", () => expect(deriveSuggestedPracticeStatus(practice("sent"), [item("requested")])).toBe("sent")); });
describe("tenant isolation", () => { it("throws on mismatched organization", () => expect(() => assertSameOrganization("org-1", [{ organizationId: "org-2" }])).toThrow("Record does not belong")); });
function practice(status: Practice["status"]): Pick<Practice, "status"> { return { status }; }
function item(status: PracticeItem["status"], required = true): Pick<PracticeItem, "required" | "status"> { return { status, required }; }
