import { describe, expect, it } from "vitest";
import { MAX_UPLOAD_FILE_SIZE_BYTES } from "@/lib/domain/document-upload";
import { createEmptyStudioState, InMemoryStudioRepository } from "@/lib/studio/memory-store";

describe("studio repository", () => {
  it("seeds the default template once", async () => { const repository = new InMemoryStudioRepository(createEmptyStudioState()); const first = await repository.ensureDefault730Template(); const second = await repository.ensureDefault730Template(); expect(first.template.id).toBe(second.template.id); expect(second.items).toHaveLength(29); });
  it("creates a practice from template", async () => { const repository = new InMemoryStudioRepository(createEmptyStudioState()); const client = await repository.createClient("org-1", { firstName: "Mario", lastName: "Rossi" }); const practice = await repository.createPractice("org-1", client.id, 2025); const detail = await repository.getPracticeDetail("org-1", practice.id); expect(detail?.items).toHaveLength(29); expect(detail?.missingItemCount).toBe(29); expect(detail?.progress).toBe(0); });
  it("isolates clients and practices by organization", async () => { const repository = new InMemoryStudioRepository(createEmptyStudioState()); const client = await repository.createClient("org-1", { firstName: "Mario", lastName: "Rossi" }); await repository.createClient("org-2", { firstName: "Giulia", lastName: "Bianchi" }); const practice = await repository.createPractice("org-1", client.id, 2025); const detail = await repository.getPracticeDetail("org-1", practice.id); await expect(repository.getPracticeDetail("org-2", practice.id)).resolves.toBeNull(); await expect(repository.createPractice("org-2", client.id, 2025)).rejects.toThrow("Client not found."); await expect(repository.updatePracticeItem("org-2", detail!.items[0].id, { status: "approved", required: true, note: null })).rejects.toThrow("Practice item not found."); });
  it("updates item and recalculates progress", async () => { const repository = new InMemoryStudioRepository(createEmptyStudioState()); const client = await repository.createClient("org-1", { firstName: "Mario", lastName: "Rossi" }); const practice = await repository.createPractice("org-1", client.id, 2025); const detail = await repository.getPracticeDetail("org-1", practice.id); await repository.updatePracticeItem("org-1", detail!.items[0].id, { status: "approved", required: true, note: "ok" }); const updated = await repository.getPracticeDetail("org-1", practice.id); expect(updated?.progress).toBe(1 / 29); expect(updated?.missingItemCount).toBe(28); });
  it("computes dashboard metrics", async () => { const repository = new InMemoryStudioRepository(createEmptyStudioState()); const client = await repository.createClient("org-1", { firstName: "Giulia", lastName: "Bianchi" }); const practice = await repository.createPractice("org-1", client.id, 2025); const detail = await repository.getPracticeDetail("org-1", practice.id); await repository.updatePracticeStatus("org-1", practice.id, "needs_review"); await repository.updatePracticeItem("org-1", detail!.items[0].id, { status: "approved", required: true, note: null }); const dashboard = await repository.getDashboard("org-1"); expect(dashboard.totalPractices).toBe(1); expect(dashboard.needsReview).toBe(1); expect(dashboard.totalMissingDocuments).toBe(28); });
  it("returns null for invalid or disabled public tokens", async () => { const state = createEmptyStudioState(); const repository = new InMemoryStudioRepository(state); const client = await repository.createClient("org-1", { firstName: "Mario", lastName: "Rossi" }); const practice = await repository.createPractice("org-1", client.id, 2025); await expect(repository.getPublicPractice("invalid")).resolves.toBeNull(); await repository.setPracticePublicLinkEnabled("org-1", practice.id, false); await expect(repository.getPublicPractice(practice.publicToken)).resolves.toBeNull(); expect(state.activityLogEvents.some((e) => e.eventType === "public_link_disabled")).toBe(true); });
  it("returns one practice for valid public token", async () => { const repository = new InMemoryStudioRepository(createEmptyStudioState()); const firstClient = await repository.createClient("org-1", { firstName: "Mario", lastName: "Rossi" }); const secondClient = await repository.createClient("org-2", { firstName: "Giulia", lastName: "Bianchi" }); const firstPractice = await repository.createPractice("org-1", firstClient.id, 2025); const secondPractice = await repository.createPractice("org-2", secondClient.id, 2025); const portal = await repository.getPublicPractice(firstPractice.publicToken); expect(portal?.practice.id).toBe(firstPractice.id); expect(portal?.practice.id).not.toBe(secondPractice.id); });
  it("blocks uploads for archived practices", async () => { const repository = new InMemoryStudioRepository(createEmptyStudioState()); const client = await repository.createClient("org-1", { firstName: "Mario", lastName: "Rossi" }); const practice = await repository.createPractice("org-1", client.id, 2025); const detail = await repository.getPracticeDetail("org-1", practice.id); await repository.updatePracticeStatus("org-1", practice.id, "archived"); await expect(repository.uploadClientDocument(practice.publicToken, detail!.items[0].id, uploadFile("doc.pdf", "application/pdf"))).rejects.toThrow("archiviata"); });
  it("validates upload MIME type, size, and item ownership", async () => { const repository = new InMemoryStudioRepository(createEmptyStudioState()); const client = await repository.createClient("org-1", { firstName: "Mario", lastName: "Rossi" }); const practice = await repository.createPractice("org-1", client.id, 2025); const detail = await repository.getPracticeDetail("org-1", practice.id); await expect(repository.uploadClientDocument(practice.publicToken, detail!.items[0].id, uploadFile("doc.txt", "text/plain"))).rejects.toThrow("Formato file"); await expect(repository.uploadClientDocument(practice.publicToken, detail!.items[0].id, uploadFile("doc.pdf", "application/pdf", MAX_UPLOAD_FILE_SIZE_BYTES + 1))).rejects.toThrow("25 MB"); await expect(repository.uploadClientDocument(practice.publicToken, "other-item", uploadFile("doc.pdf", "application/pdf"))).rejects.toThrow("Documento non trovato"); });
  it("creates document, updates status, logs activity, and signs URLs", async () => { const state = createEmptyStudioState(); const repository = new InMemoryStudioRepository(state); const client = await repository.createClient("org-1", { firstName: "Mario", lastName: "Rossi" }); const practice = await repository.createPractice("org-1", client.id, 2025); const detail = await repository.getPracticeDetail("org-1", practice.id); const document = await repository.uploadClientDocument(practice.publicToken, detail!.items[0].id, uploadFile("doc.pdf", "application/pdf")); const updated = await repository.getPracticeDetail("org-1", practice.id); const signedUrl = await repository.createDocumentSignedUrl("org-1", document.id); expect(updated?.items[0].status).toBe("uploaded"); expect(updated?.practice.status).toBe("needs_review"); expect(updated?.documents).toHaveLength(1); expect(signedUrl).toContain(document.id); expect(state.activityLogEvents.some((e) => e.eventType === "document_uploaded")).toBe(true); });
});
function uploadFile(name: string, type: string, size = 1024) { return { name, type, size, async arrayBuffer() { return new ArrayBuffer(size); } }; }
