export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type TimestampColumns = { created_at: string; updated_at: string };
type TimestampInsert = { created_at?: string; updated_at?: string };
type TimestampUpdate = { updated_at?: string };

export type Database = {
  public: {
    Tables: {
      profiles: { Row: TimestampColumns & { id: string; email: string; full_name: string | null }; Insert: TimestampInsert & { id: string; email: string; full_name?: string | null }; Update: TimestampUpdate & { email?: string; full_name?: string | null }; Relationships: [] };
      organizations: { Row: TimestampColumns & { id: string; name: string; slug: string; owner_id: string }; Insert: TimestampInsert & { id?: string; name: string; slug: string; owner_id: string }; Update: TimestampUpdate & { name?: string; slug?: string }; Relationships: [] };
      organization_members: { Row: TimestampColumns & { id: string; organization_id: string; user_id: string; role: Database["public"]["Enums"]["organization_role"] }; Insert: TimestampInsert & { id?: string; organization_id: string; user_id: string; role?: Database["public"]["Enums"]["organization_role"] }; Update: TimestampUpdate & { role?: Database["public"]["Enums"]["organization_role"] }; Relationships: [] };
      client_profiles: { Row: TimestampColumns & { id: string; organization_id: string; first_name: string; last_name: string; email: string | null; phone: string | null; tax_code: string | null; status: Database["public"]["Enums"]["client_status"] }; Insert: TimestampInsert & { id?: string; organization_id: string; first_name: string; last_name: string; email?: string | null; phone?: string | null; tax_code?: string | null; status?: Database["public"]["Enums"]["client_status"] }; Update: TimestampUpdate & { first_name?: string; last_name?: string; email?: string | null; phone?: string | null; tax_code?: string | null; status?: Database["public"]["Enums"]["client_status"] }; Relationships: [] };
      checklist_templates: { Row: TimestampColumns & { id: string; organization_id: string | null; key: string; name: string; description: string | null; is_default: boolean }; Insert: TimestampInsert & { id?: string; organization_id?: string | null; key: string; name: string; description?: string | null; is_default?: boolean }; Update: TimestampUpdate & { organization_id?: string | null; key?: string; name?: string; description?: string | null; is_default?: boolean }; Relationships: [] };
      checklist_template_categories: { Row: TimestampColumns & { id: string; template_id: string; name: string; sort_order: number }; Insert: TimestampInsert & { id?: string; template_id: string; name: string; sort_order?: number }; Update: TimestampUpdate & { name?: string; sort_order?: number }; Relationships: [] };
      checklist_template_items: { Row: TimestampColumns & { id: string; template_id: string; category_id: string; label: string; required: boolean; sort_order: number }; Insert: TimestampInsert & { id?: string; template_id: string; category_id: string; label: string; required?: boolean; sort_order?: number }; Update: TimestampUpdate & { category_id?: string; label?: string; required?: boolean; sort_order?: number }; Relationships: [] };
      practices: { Row: TimestampColumns & { id: string; organization_id: string; client_id: string; template_id: string; fiscal_year: number; status: Database["public"]["Enums"]["practice_status"]; public_token: string; public_link_enabled: boolean; archived_at: string | null; reminder_enabled: boolean; last_reminder_sent_at: string | null; reminder_count: number }; Insert: TimestampInsert & { id?: string; organization_id: string; client_id: string; template_id: string; fiscal_year: number; status?: Database["public"]["Enums"]["practice_status"]; public_token?: string; public_link_enabled?: boolean; archived_at?: string | null; reminder_enabled?: boolean; last_reminder_sent_at?: string | null; reminder_count?: number }; Update: TimestampUpdate & { status?: Database["public"]["Enums"]["practice_status"]; public_token?: string; public_link_enabled?: boolean; archived_at?: string | null; reminder_enabled?: boolean; last_reminder_sent_at?: string | null; reminder_count?: number }; Relationships: [] };
      practice_items: { Row: TimestampColumns & { id: string; organization_id: string; practice_id: string; template_item_id: string; category_name: string; label: string; required: boolean; status: Database["public"]["Enums"]["practice_item_status"]; note: string | null; note_to_client: string | null; sort_order: number }; Insert: TimestampInsert & { id?: string; organization_id: string; practice_id: string; template_item_id: string; category_name: string; label: string; required?: boolean; status?: Database["public"]["Enums"]["practice_item_status"]; note?: string | null; note_to_client?: string | null; sort_order?: number }; Update: TimestampUpdate & { required?: boolean; status?: Database["public"]["Enums"]["practice_item_status"]; note?: string | null; note_to_client?: string | null }; Relationships: [] };
      client_requests: { Row: TimestampColumns & { id: string; organization_id: string; client_id: string; title: string; description: string | null; status: Database["public"]["Enums"]["request_status"]; due_at: string | null }; Insert: TimestampInsert & { id?: string; organization_id: string; client_id: string; title: string; description?: string | null; status?: Database["public"]["Enums"]["request_status"]; due_at?: string | null }; Update: TimestampUpdate & { title?: string; description?: string | null; status?: Database["public"]["Enums"]["request_status"]; due_at?: string | null }; Relationships: [] };
      document_records: { Row: TimestampColumns & { id: string; organization_id: string; client_id: string; practice_id: string | null; practice_item_id: string | null; request_id: string | null; storage_path: string; file_name: string; content_type: string | null; size_bytes: number | null; original_file_name: string; stored_file_name: string; mime_type: string; file_size_bytes: number; uploaded_by_type: Database["public"]["Enums"]["document_uploaded_by_type"]; status: Database["public"]["Enums"]["document_status"] }; Insert: TimestampInsert & { id?: string; organization_id: string; client_id: string; practice_id?: string | null; practice_item_id?: string | null; request_id?: string | null; storage_path: string; file_name: string; content_type?: string | null; size_bytes?: number | null; original_file_name?: string; stored_file_name?: string; mime_type?: string; file_size_bytes?: number; uploaded_by_type?: Database["public"]["Enums"]["document_uploaded_by_type"]; status?: Database["public"]["Enums"]["document_status"] }; Update: TimestampUpdate & { practice_id?: string | null; practice_item_id?: string | null; request_id?: string | null; storage_path?: string; file_name?: string; content_type?: string | null; size_bytes?: number | null; original_file_name?: string; stored_file_name?: string; mime_type?: string; file_size_bytes?: number; uploaded_by_type?: Database["public"]["Enums"]["document_uploaded_by_type"]; status?: Database["public"]["Enums"]["document_status"] }; Relationships: [] };
      reminders: { Row: TimestampColumns & { id: string; organization_id: string; practice_id: string; channel: Database["public"]["Enums"]["reminder_channel"]; reminder_type: Database["public"]["Enums"]["reminder_type"]; target_item_id: string | null; status: Database["public"]["Enums"]["reminder_status"]; sent_at: string; payload: Json; error_message: string | null }; Insert: TimestampInsert & { id?: string; organization_id: string; practice_id: string; channel?: Database["public"]["Enums"]["reminder_channel"]; reminder_type: Database["public"]["Enums"]["reminder_type"]; target_item_id?: string | null; status: Database["public"]["Enums"]["reminder_status"]; sent_at?: string; payload?: Json; error_message?: string | null }; Update: TimestampUpdate & { status?: Database["public"]["Enums"]["reminder_status"]; payload?: Json; error_message?: string | null }; Relationships: [] };
      activity_log_events: { Row: TimestampColumns & { id: string; organization_id: string; practice_id: string | null; practice_item_id: string | null; document_id: string | null; event_type: Database["public"]["Enums"]["activity_event_type"]; actor_type: Database["public"]["Enums"]["activity_actor_type"]; metadata: Json }; Insert: TimestampInsert & { id?: string; organization_id: string; practice_id?: string | null; practice_item_id?: string | null; document_id?: string | null; event_type: Database["public"]["Enums"]["activity_event_type"]; actor_type: Database["public"]["Enums"]["activity_actor_type"]; metadata?: Json }; Update: TimestampUpdate & { document_id?: string | null; metadata?: Json }; Relationships: [] };
    };
    Enums: {
      organization_role: "owner" | "admin" | "member";
      client_status: "active" | "archived";
      request_status: "draft" | "sent" | "in_progress" | "completed" | "archived";
      practice_status: "draft" | "sent" | "in_progress" | "needs_review" | "complete" | "archived";
      practice_item_status: "requested" | "uploaded" | "needs_correction" | "approved" | "not_needed";
      document_uploaded_by_type: "client" | "studio";
      document_status: "active" | "deleted";
      activity_event_type: "public_link_opened" | "document_uploaded" | "document_deleted" | "public_link_disabled" | "public_link_enabled" | "reminder_sent" | "reminder_failed" | "correction_notification_sent" | "correction_notification_failed" | "item_marked_needs_correction" | "item_approved" | "item_marked_not_needed";
      reminder_channel: "email";
      reminder_type: "missing_documents" | "correction";
      reminder_status: "sent" | "failed";
      activity_actor_type: "client" | "studio" | "system";
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
