"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import type { PracticeItemStatus, PracticeStatus } from "@/types/models";
import { getCurrentOrganization } from "@/lib/studio/organization-context";
import { getStudioRepository } from "@/lib/studio/repository";
import { sendCorrectionNotification, sendMissingDocumentsReminder } from "@/lib/studio/reminder-service";

function requiredString(formData: FormData, key: string) { const value = formData.get(key); if (typeof value !== "string" || !value.trim()) throw new Error(`Missing required field: ${key}.`); return value.trim(); }
function optionalString(formData: FormData, key: string) { const value = formData.get(key); return typeof value === "string" ? value.trim() : ""; }
export async function createClientAction(formData: FormData) { const org = await getCurrentOrganization(); const repo = getStudioRepository(); const client = await repo.createClient(org.id, { firstName: requiredString(formData, "firstName"), lastName: requiredString(formData, "lastName"), email: optionalString(formData, "email"), phone: optionalString(formData, "phone"), taxCode: optionalString(formData, "taxCode") }); revalidatePath("/clients"); redirect(`/clients/${client.id}`); }
export async function updateClientAction(formData: FormData) { const org = await getCurrentOrganization(); const repo = getStudioRepository(); const clientId = requiredString(formData, "clientId"); await repo.updateClient(org.id, clientId, { firstName: requiredString(formData, "firstName"), lastName: requiredString(formData, "lastName"), email: optionalString(formData, "email"), phone: optionalString(formData, "phone"), taxCode: optionalString(formData, "taxCode") }); revalidatePath("/clients"); revalidatePath(`/clients/${clientId}`); }
export async function archiveClientAction(formData: FormData) { const org = await getCurrentOrganization(); const clientId = requiredString(formData, "clientId"); await getStudioRepository().archiveClient(org.id, clientId); revalidatePath("/clients"); revalidatePath(`/clients/${clientId}`); }
export async function createPracticeAction(formData: FormData) { const org = await getCurrentOrganization(); const repo = getStudioRepository(); const practice = await repo.createPractice(org.id, requiredString(formData, "clientId"), Number(requiredString(formData, "fiscalYear"))); revalidatePath("/practices"); redirect(`/practices/${practice.id}`); }
export async function updatePracticeStatusAction(formData: FormData) { const org = await getCurrentOrganization(); const practiceId = requiredString(formData, "practiceId"); await getStudioRepository().updatePracticeStatus(org.id, practiceId, requiredString(formData, "status") as PracticeStatus); revalidatePath("/dashboard"); revalidatePath("/practices"); revalidatePath(`/practices/${practiceId}`); }
export async function updatePracticeItemAction(formData: FormData) { const org = await getCurrentOrganization(); const practiceId = requiredString(formData, "practiceId"); const status = requiredString(formData, "status") as PracticeItemStatus; const note = optionalString(formData, "note"); const noteToClient = optionalString(formData, "noteToClient") || note; if (status === "needs_correction" && !noteToClient) throw new Error("Aggiungi una nota per il cliente prima di segnare il documento come da correggere."); await getStudioRepository().updatePracticeItem(org.id, requiredString(formData, "practiceItemId"), { status, required: formData.get("required") === "on", note, noteToClient }); revalidatePath("/dashboard"); revalidatePath("/practices"); revalidatePath(`/practices/${practiceId}`); }
export async function setPracticePublicLinkEnabledAction(formData: FormData) { const org = await getCurrentOrganization(); const practiceId = requiredString(formData, "practiceId"); await getStudioRepository().setPracticePublicLinkEnabled(org.id, practiceId, requiredString(formData, "enabled") === "true"); revalidatePath(`/practices/${practiceId}`); }
export async function deletePracticeDocumentAction(formData: FormData) { const org = await getCurrentOrganization(); const practiceId = requiredString(formData, "practiceId"); await getStudioRepository().deleteDocument(org.id, requiredString(formData, "documentId")); revalidatePath(`/practices/${practiceId}`); }

export async function sendPracticeReminderAction(formData: FormData) { const org = await getCurrentOrganization(); const practiceId = requiredString(formData, "practiceId"); await sendMissingDocumentsReminder({ organizationId: org.id, practiceId }); revalidatePath(`/practices/${practiceId}`); }
export async function sendItemReminderAction(formData: FormData) { const org = await getCurrentOrganization(); const practiceId = requiredString(formData, "practiceId"); await sendMissingDocumentsReminder({ organizationId: org.id, practiceId, targetItemId: requiredString(formData, "practiceItemId") }); revalidatePath(`/practices/${practiceId}`); }
export async function sendCorrectionNotificationAction(formData: FormData) { const org = await getCurrentOrganization(); const practiceId = requiredString(formData, "practiceId"); await sendCorrectionNotification({ organizationId: org.id, practiceId, practiceItemId: requiredString(formData, "practiceItemId") }); revalidatePath(`/practices/${practiceId}`); }
