import { buildDefault730Template, findDefault730Template } from "@/lib/domain/checklist-template";
import { assertCanAddFileToPracticeItem, sanitizeFileName, validateUploadFile } from "@/lib/domain/document-upload";
import { assertSameOrganization, calculatePracticeProgress, countMissingRequiredItems, createPracticeFromTemplate, deriveSuggestedPracticeStatus } from "@/lib/domain/practice";
import type { ActivityLogInput, ClientInput, PracticeDetail, PracticeSummary, ReminderRecordInput, StudioDashboard, StudioRepository } from "@/lib/studio/studio-repository";
import type { ActivityLogEvent, ChecklistTemplate, ChecklistTemplateCategory, ChecklistTemplateItem, ClientProfile, DocumentRecord, ID, Organization, Practice, PracticeItem, PracticeItemStatus, PracticeStatus, ReminderRecord } from "@/types/models";

type StoreState = { templates: ChecklistTemplate[]; categories: ChecklistTemplateCategory[]; templateItems: ChecklistTemplateItem[]; clients: ClientProfile[]; practices: Practice[]; practiceItems: PracticeItem[]; documents: DocumentRecord[]; activityLogEvents: ActivityLogEvent[]; reminders: ReminderRecord[] };
export function createEmptyStudioState(): StoreState { return { templates: [], categories: [], templateItems: [], clients: [], practices: [], practiceItems: [], documents: [], activityLogEvents: [], reminders: [] }; }
const sharedState = createEmptyStudioState();
function now() { return new Date().toISOString(); }
function createId() { return crypto.randomUUID(); }
function createPublicToken() { const bytes = new Uint8Array(32); crypto.getRandomValues(bytes); return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join(""); }
function normalizeText(value: string | null | undefined) { return value?.trim() || null; }
function sortByUpdatedAtDesc<T extends { updatedAt: string }>(items: T[]) { return [...items].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }

export class InMemoryStudioRepository implements StudioRepository {
  constructor(private readonly state: StoreState = sharedState) {}
  async ensureDefault730Template() { const existing = findDefault730Template(this.state.templates); if (existing) return { template: existing, categories: this.state.categories.filter((c) => c.templateId === existing.id), items: this.state.templateItems.filter((i) => i.templateId === existing.id) }; const seeded = buildDefault730Template(createId, now); this.state.templates.push(seeded.template); this.state.categories.push(...seeded.categories); this.state.templateItems.push(...seeded.items); return seeded; }
  async getOrganization(organizationId: ID) { return { id: organizationId, name: "Studio Demo", slug: "studio-demo" }; }
  async listClients(organizationId: ID, search?: string) { const query = search?.trim().toLowerCase(); const clients = this.state.clients.filter((c) => c.organizationId === organizationId); if (!query) return sortByUpdatedAtDesc(clients); return sortByUpdatedAtDesc(clients.filter((c) => [c.firstName, c.lastName, c.email, c.phone, c.taxCode].filter(Boolean).join(" ").toLowerCase().includes(query))); }
  async getClient(organizationId: ID, clientId: ID) { return this.state.clients.find((c) => c.organizationId === organizationId && c.id === clientId) ?? null; }
  async createClient(organizationId: ID, input: ClientInput) { const timestamp = now(); const client: ClientProfile = { id: createId(), organizationId, firstName: input.firstName.trim(), lastName: input.lastName.trim(), email: normalizeText(input.email), phone: normalizeText(input.phone), taxCode: normalizeText(input.taxCode)?.toUpperCase() ?? null, status: "active", createdAt: timestamp, updatedAt: timestamp }; this.state.clients.push(client); return client; }
  async updateClient(organizationId: ID, clientId: ID, input: ClientInput) { const client = await this.getClient(organizationId, clientId); if (!client) throw new Error("Client not found."); client.firstName = input.firstName.trim(); client.lastName = input.lastName.trim(); client.email = normalizeText(input.email); client.phone = normalizeText(input.phone); client.taxCode = normalizeText(input.taxCode)?.toUpperCase() ?? null; client.updatedAt = now(); return client; }
  async archiveClient(organizationId: ID, clientId: ID) { const client = await this.getClient(organizationId, clientId); if (!client) throw new Error("Client not found."); client.status = "archived"; client.updatedAt = now(); }
  async createPractice(organizationId: ID, clientId: ID, fiscalYear: number) { const client = await this.getClient(organizationId, clientId); if (!client) throw new Error("Client not found."); assertSameOrganization(organizationId, [client]); const seeded = await this.ensureDefault730Template(); const { practice, practiceItems } = createPracticeFromTemplate({ organizationId, clientId, fiscalYear, template: seeded.template, categories: seeded.categories, templateItems: seeded.items, createId, createPublicToken, now }); this.state.practices.push(practice); this.state.practiceItems.push(...practiceItems); return practice; }
  async listPractices(organizationId: ID) { return this.state.practices.filter((p) => p.organizationId === organizationId).map((p) => this.toPracticeSummary(p)).filter((s): s is PracticeSummary => s !== null).sort((a, b) => b.practice.updatedAt.localeCompare(a.practice.updatedAt)); }
  async getPracticeDetail(organizationId: ID, practiceId: ID) { const practice = this.state.practices.find((p) => p.organizationId === organizationId && p.id === practiceId); if (!practice) return null; const summary = this.toPracticeSummary(practice); if (!summary) return null; const items = this.state.practiceItems.filter((i) => i.organizationId === organizationId && i.practiceId === practice.id).sort((a, b) => a.sortOrder - b.sortOrder); const documents = await this.listPracticeDocuments(organizationId, practice.id); return { ...summary, items, documents }; }
  async getPublicPractice(publicToken: string) { const practice = this.state.practices.find((p) => p.publicToken === publicToken && p.publicLinkEnabled); if (!practice) return null; const detail = await this.getPracticeDetail(practice.organizationId, practice.id); if (!detail) return null; return { ...detail, organization: { id: practice.organizationId, name: "Studio Demo", slug: "studio-demo" }, canUpload: practice.status !== "archived" }; }
  async logPublicLinkOpened(publicToken: string) { const practice = this.state.practices.find((p) => p.publicToken === publicToken); if (practice) this.log(practice.organizationId, practice.id, null, null, "public_link_opened", "client", {}); }
  async updatePracticeStatus(organizationId: ID, practiceId: ID, status: PracticeStatus) { const detail = await this.getPracticeDetail(organizationId, practiceId); if (!detail) throw new Error("Practice not found."); detail.practice.status = status; detail.practice.archivedAt = status === "archived" ? now() : null; detail.practice.updatedAt = now(); return detail.practice; }
  async updatePracticeItem(organizationId: ID, practiceItemId: ID, input: { status: PracticeItemStatus; required: boolean; note?: string | null; noteToClient?: string | null }) { const item = this.state.practiceItems.find((i) => i.organizationId === organizationId && i.id === practiceItemId); if (!item) throw new Error("Practice item not found."); const noteToClient = normalizeText(input.noteToClient ?? input.note); if (input.status === "needs_correction" && !noteToClient) throw new Error("Aggiungi una nota per il cliente prima di segnare il documento come da correggere."); item.status = input.status; item.required = input.required; item.note = normalizeText(input.note); item.noteToClient = noteToClient; item.updatedAt = now(); const practice = this.state.practices.find((p) => p.id === item.practiceId); if (practice) practice.updatedAt = item.updatedAt; const eventByStatus: Partial<Record<PracticeItemStatus, ActivityLogEvent["eventType"]>> = { needs_correction: "item_marked_needs_correction", approved: "item_approved", not_needed: "item_marked_not_needed" }; const eventType = eventByStatus[input.status]; if (eventType) this.log(organizationId, item.practiceId, item.id, null, eventType, "studio", { noteToClient }); return item; }
  async setPracticePublicLinkEnabled(organizationId: ID, practiceId: ID, enabled: boolean) { const detail = await this.getPracticeDetail(organizationId, practiceId); if (!detail) throw new Error("Practice not found."); detail.practice.publicLinkEnabled = enabled; detail.practice.updatedAt = now(); this.log(organizationId, practiceId, null, null, enabled ? "public_link_enabled" : "public_link_disabled", "studio", {}); return detail.practice; }
  async uploadClientDocument(publicToken: string, practiceItemId: ID, file: Parameters<StudioRepository["uploadClientDocument"]>[2]) { validateUploadFile(file); const portal = await this.getPublicPractice(publicToken); if (!portal) throw new Error("Link non valido o disabilitato."); if (!portal.canUpload) throw new Error("Questa pratica e archiviata e non accetta nuovi caricamenti."); const item = portal.items.find((i) => i.id === practiceItemId); if (!item) throw new Error("Documento non trovato per questa pratica."); if (item.status === "approved" || item.status === "not_needed") throw new Error("Questo documento e gia completato."); assertCanAddFileToPracticeItem(portal.documents.filter((d) => d.practiceItemId === practiceItemId && d.status === "active").length); const timestamp = now(); const documentId = createId(); const safeFileName = sanitizeFileName(file.name); const document: DocumentRecord = { id: documentId, organizationId: portal.practice.organizationId, clientId: portal.practice.clientId, practiceId: portal.practice.id, practiceItemId, requestId: null, storagePath: `org-${portal.practice.organizationId}/practice-${portal.practice.id}/item-${practiceItemId}/${documentId}-${safeFileName}`, fileName: file.name, contentType: file.type, sizeBytes: file.size, originalFileName: file.name, storedFileName: `${documentId}-${safeFileName}`, mimeType: file.type, fileSizeBytes: file.size, uploadedByType: "client", status: "active", createdAt: timestamp, updatedAt: timestamp }; this.state.documents.push(document); item.status = "uploaded"; item.updatedAt = timestamp; const items = this.state.practiceItems.filter((i) => i.organizationId === portal.practice.organizationId && i.practiceId === portal.practice.id); portal.practice.status = deriveSuggestedPracticeStatus(portal.practice, items); portal.practice.updatedAt = timestamp; this.log(document.organizationId, document.practiceId, practiceItemId, documentId, "document_uploaded", "client", { mimeType: file.type, fileSizeBytes: file.size }); return document; }
  async listPracticeDocuments(organizationId: ID, practiceId: ID) { return this.state.documents.filter((d) => d.organizationId === organizationId && d.practiceId === practiceId && d.status === "active").sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
  async createDocumentSignedUrl(organizationId: ID, documentId: ID) { const document = this.state.documents.find((d) => d.organizationId === organizationId && d.id === documentId); if (!document) throw new Error("Document not found."); return `/memory-download/${document.id}`; }
  async deleteDocument(organizationId: ID, documentId: ID) { const document = this.state.documents.find((d) => d.organizationId === organizationId && d.id === documentId); if (!document) throw new Error("Document not found."); document.status = "deleted"; document.updatedAt = now(); this.log(organizationId, document.practiceId, document.practiceItemId, documentId, "document_deleted", "studio", {}); }
  async getDashboard(organizationId: ID): Promise<StudioDashboard> { const practices = await this.listPractices(organizationId); return { totalPractices: practices.length, inProgress: practices.filter((s) => s.practice.status === "in_progress").length, needsReview: practices.filter((s) => s.practice.status === "needs_review").length, complete: practices.filter((s) => s.practice.status === "complete").length, totalMissingDocuments: practices.reduce((t, s) => t + s.missingItemCount, 0), recentPractices: practices.slice(0, 5) }; }
  async createReminderRecord(input: ReminderRecordInput) { const timestamp = now(); const record: ReminderRecord = { id: createId(), organizationId: input.organizationId, practiceId: input.practiceId, channel: input.channel, reminderType: input.reminderType, targetItemId: input.targetItemId ?? null, status: input.status, sentAt: input.sentAt, payload: input.payload, errorMessage: input.errorMessage ?? null, createdAt: timestamp, updatedAt: timestamp }; this.state.reminders.push(record); return record; }
  async markPracticeReminderSent(organizationId: ID, practiceId: ID, sentAt: string) { const practice = this.state.practices.find((p) => p.organizationId === organizationId && p.id === practiceId); if (!practice) throw new Error("Practice not found."); practice.lastReminderSentAt = sentAt; practice.reminderCount += 1; practice.updatedAt = sentAt; }
  async recordActivityEvent(input: ActivityLogInput) { this.log(input.organizationId, input.practiceId, input.practiceItemId, input.documentId, input.eventType, input.actorType, input.metadata); }
  async listReminderCandidates(_intervalDays: number) { const rows: Array<PracticeDetail & { organization: Pick<Organization, "id" | "name" | "slug"> }> = []; for (const practice of this.state.practices.filter((p) => p.publicLinkEnabled && p.reminderEnabled && !p.archivedAt && ["sent", "in_progress", "needs_review"].includes(p.status))) { const detail = await this.getPracticeDetail(practice.organizationId, practice.id); if (detail) rows.push({ ...detail, organization: await this.getOrganization(practice.organizationId) }); } return rows; }
  private toPracticeSummary(practice: Practice): PracticeSummary | null { const client = this.state.clients.find((c) => c.organizationId === practice.organizationId && c.id === practice.clientId); if (!client) return null; const items = this.state.practiceItems.filter((i) => i.practiceId === practice.id); return { practice, client, progress: calculatePracticeProgress(items), missingItemCount: countMissingRequiredItems(items) }; }
  private log(organizationId: ID, practiceId: ID | null, practiceItemId: ID | null, documentId: ID | null, eventType: ActivityLogEvent["eventType"], actorType: ActivityLogEvent["actorType"], metadata: Record<string, unknown>) { const timestamp = now(); this.state.activityLogEvents.push({ id: createId(), organizationId, practiceId, practiceItemId, documentId, eventType, actorType, metadata, createdAt: timestamp, updatedAt: timestamp }); }
}
