import "server-only";

import { DEFAULT_730_TEMPLATE_DEFINITION, DEFAULT_730_TEMPLATE_KEY, buildDefault730Template } from "@/lib/domain/checklist-template";
import { assertCanAddFileToPracticeItem, sanitizeFileName, validateUploadFile } from "@/lib/domain/document-upload";
import { assertSameOrganization, calculatePracticeProgress, countMissingRequiredItems, createPracticeFromTemplate, deriveSuggestedPracticeStatus } from "@/lib/domain/practice";
import { createServiceSupabaseClient } from "@/lib/db/supabase";
import { env } from "@/lib/env";
import { SupabaseStorageProvider } from "@/lib/storage";
import type { StorageProvider } from "@/lib/storage";
import type { ClientInput, PracticeSummary, StudioDashboard, StudioRepository } from "@/lib/studio/studio-repository";
import type { ChecklistTemplateCategory, ChecklistTemplateItem, ClientProfile, DocumentRecord, ID, Organization, Practice, PracticeItem, PracticeItemStatus, PracticeStatus } from "@/types/models";
import type { Database } from "@/types/database";

type SupabaseClient = ReturnType<typeof createServiceSupabaseClient>;
type ClientRow = Database["public"]["Tables"]["client_profiles"]["Row"];
type TemplateRow = Database["public"]["Tables"]["checklist_templates"]["Row"];
type CategoryRow = Database["public"]["Tables"]["checklist_template_categories"]["Row"];
type TemplateItemRow = Database["public"]["Tables"]["checklist_template_items"]["Row"];
type PracticeRow = Database["public"]["Tables"]["practices"]["Row"];
type PracticeItemRow = Database["public"]["Tables"]["practice_items"]["Row"];
type DocumentRow = Database["public"]["Tables"]["document_records"]["Row"];
type OrganizationRow = Database["public"]["Tables"]["organizations"]["Row"];

function createId() { return crypto.randomUUID(); }
function createPublicToken() { const bytes = new Uint8Array(32); crypto.getRandomValues(bytes); return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join(""); }
function now() { return new Date().toISOString(); }
function normalizeText(value: string | null | undefined) { return value?.trim() || null; }
function normalizeTaxCode(value: string | null | undefined) { return normalizeText(value)?.toUpperCase() ?? null; }
function throwIfError(error: { message: string } | null, message: string) { if (error) throw new Error(`${message}: ${error.message}`); }
function requireData<T>(data: T | null, message: string): T { if (!data) throw new Error(message); return data; }
function mapClient(row: ClientRow): ClientProfile { return { id: row.id, organizationId: row.organization_id, firstName: row.first_name, lastName: row.last_name, email: row.email, phone: row.phone, taxCode: row.tax_code, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapTemplate(row: TemplateRow) { return { id: row.id, organizationId: row.organization_id, key: row.key, name: row.name, description: row.description, isDefault: row.is_default, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapCategory(row: CategoryRow): ChecklistTemplateCategory { return { id: row.id, templateId: row.template_id, name: row.name, sortOrder: row.sort_order, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapTemplateItem(row: TemplateItemRow): ChecklistTemplateItem { return { id: row.id, templateId: row.template_id, categoryId: row.category_id, label: row.label, required: row.required, sortOrder: row.sort_order, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapPractice(row: PracticeRow): Practice { return { id: row.id, organizationId: row.organization_id, clientId: row.client_id, templateId: row.template_id, fiscalYear: row.fiscal_year, status: row.status, publicToken: row.public_token, publicLinkEnabled: row.public_link_enabled, archivedAt: row.archived_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapPracticeItem(row: PracticeItemRow): PracticeItem { return { id: row.id, organizationId: row.organization_id, practiceId: row.practice_id, templateItemId: row.template_item_id, categoryName: row.category_name, label: row.label, required: row.required, status: row.status, note: row.note, sortOrder: row.sort_order, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapDocument(row: DocumentRow): DocumentRecord { return { id: row.id, organizationId: row.organization_id, clientId: row.client_id, practiceId: row.practice_id, practiceItemId: row.practice_item_id, requestId: row.request_id, storagePath: row.storage_path, fileName: row.file_name, contentType: row.content_type, sizeBytes: row.size_bytes, originalFileName: row.original_file_name || row.file_name, storedFileName: row.stored_file_name || row.file_name, mimeType: row.mime_type || row.content_type || "application/octet-stream", fileSizeBytes: row.file_size_bytes || row.size_bytes || 0, uploadedByType: row.uploaded_by_type, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapOrganization(row: OrganizationRow): Pick<Organization, "id" | "name" | "slug"> { return { id: row.id, name: row.name, slug: row.slug }; }
function isExpectedDefault730Template(categories: ChecklistTemplateCategory[], items: ChecklistTemplateItem[]) { const expected = DEFAULT_730_TEMPLATE_DEFINITION.flatMap((d) => d.items.map((label) => `${d.category}:${label}`)); const categoryById = new Map(categories.map((c) => [c.id, c.name])); const actual = items.map((i) => `${categoryById.get(i.categoryId) ?? ""}:${i.label}`); return actual.length === expected.length && expected.every((item) => actual.includes(item)); }

export class SupabaseStudioRepository implements StudioRepository {
  constructor(private readonly supabase: SupabaseClient = createServiceSupabaseClient(), private readonly storage: StorageProvider = new SupabaseStorageProvider()) {}
  async ensureDefault730Template() { const existing = await this.getDefault730Template(); if (existing && isExpectedDefault730Template(existing.categories, existing.items)) return existing; if (existing) throw new Error("Default 730 checklist template exists but does not match the expected 29 checklist items."); const seeded = buildDefault730Template(createId, now); const { data, error } = await this.supabase.from("checklist_templates").insert({ id: seeded.template.id, organization_id: null, key: seeded.template.key, name: seeded.template.name, description: seeded.template.description, is_default: seeded.template.isDefault, created_at: seeded.template.createdAt, updated_at: seeded.template.updatedAt }).select().single(); if (error) { const raced = await this.getDefault730Template(); if (raced) return raced; throw new Error(`Failed to seed default 730 checklist template: ${error.message}`); } throwIfError((await this.supabase.from("checklist_template_categories").insert(seeded.categories.map((c) => ({ id: c.id, template_id: c.templateId, name: c.name, sort_order: c.sortOrder, created_at: c.createdAt, updated_at: c.updatedAt })))).error, "Failed to seed categories"); throwIfError((await this.supabase.from("checklist_template_items").insert(seeded.items.map((i) => ({ id: i.id, template_id: i.templateId, category_id: i.categoryId, label: i.label, required: i.required, sort_order: i.sortOrder, created_at: i.createdAt, updated_at: i.updatedAt })))).error, "Failed to seed items"); return { template: mapTemplate(data), categories: seeded.categories, items: seeded.items }; }
  async listClients(organizationId: ID, search?: string) { const { data, error } = await this.supabase.from("client_profiles").select().eq("organization_id", organizationId).order("updated_at", { ascending: false }); throwIfError(error, "Failed to list clients"); const clients = (data ?? []).map(mapClient); const query = search?.trim().toLowerCase(); return query ? clients.filter((c) => [c.firstName, c.lastName, c.email, c.phone, c.taxCode].filter(Boolean).join(" ").toLowerCase().includes(query)) : clients; }
  async getClient(organizationId: ID, clientId: ID) { const { data, error } = await this.supabase.from("client_profiles").select().eq("organization_id", organizationId).eq("id", clientId).maybeSingle(); throwIfError(error, "Failed to get client"); return data ? mapClient(data) : null; }
  async createClient(organizationId: ID, input: ClientInput) { const { data, error } = await this.supabase.from("client_profiles").insert({ organization_id: organizationId, first_name: input.firstName.trim(), last_name: input.lastName.trim(), email: normalizeText(input.email), phone: normalizeText(input.phone), tax_code: normalizeTaxCode(input.taxCode), status: "active" }).select().single(); throwIfError(error, "Failed to create client"); return mapClient(requireData(data, "Client was not returned.")); }
  async updateClient(organizationId: ID, clientId: ID, input: ClientInput) { const { data, error } = await this.supabase.from("client_profiles").update({ first_name: input.firstName.trim(), last_name: input.lastName.trim(), email: normalizeText(input.email), phone: normalizeText(input.phone), tax_code: normalizeTaxCode(input.taxCode) }).eq("organization_id", organizationId).eq("id", clientId).select().maybeSingle(); throwIfError(error, "Failed to update client"); return mapClient(requireData(data, "Client not found.")); }
  async archiveClient(organizationId: ID, clientId: ID) { const { data, error } = await this.supabase.from("client_profiles").update({ status: "archived" }).eq("organization_id", organizationId).eq("id", clientId).select("id").maybeSingle(); throwIfError(error, "Failed to archive client"); requireData(data, "Client not found."); }
  async createPractice(organizationId: ID, clientId: ID, fiscalYear: number) { const client = await this.getClient(organizationId, clientId); if (!client) throw new Error("Client not found."); assertSameOrganization(organizationId, [client]); const seeded = await this.ensureDefault730Template(); const { practice, practiceItems } = createPracticeFromTemplate({ organizationId, clientId, fiscalYear, template: seeded.template, categories: seeded.categories, templateItems: seeded.items, createId, createPublicToken, now }); const { data, error } = await this.supabase.from("practices").insert({ id: practice.id, organization_id: practice.organizationId, client_id: practice.clientId, template_id: practice.templateId, fiscal_year: practice.fiscalYear, status: practice.status, public_token: practice.publicToken, public_link_enabled: practice.publicLinkEnabled, archived_at: practice.archivedAt, created_at: practice.createdAt, updated_at: practice.updatedAt }).select().single(); throwIfError(error, "Failed to create practice"); throwIfError((await this.supabase.from("practice_items").insert(practiceItems.map((i) => ({ id: i.id, organization_id: i.organizationId, practice_id: i.practiceId, template_item_id: i.templateItemId, category_name: i.categoryName, label: i.label, required: i.required, status: i.status, note: i.note, sort_order: i.sortOrder, created_at: i.createdAt, updated_at: i.updatedAt })))).error, "Failed to create practice items"); return mapPractice(requireData(data, "Practice was not returned.")); }
  async listPractices(organizationId: ID) { const { data, error } = await this.supabase.from("practices").select().eq("organization_id", organizationId).order("updated_at", { ascending: false }); throwIfError(error, "Failed to list practices"); return this.toPracticeSummaries(organizationId, (data ?? []).map(mapPractice)); }
  async getPracticeDetail(organizationId: ID, practiceId: ID) { const { data, error } = await this.supabase.from("practices").select().eq("organization_id", organizationId).eq("id", practiceId).maybeSingle(); throwIfError(error, "Failed to get practice"); if (!data) return null; const practice = mapPractice(data); const summary = await this.toPracticeSummary(organizationId, practice); if (!summary) return null; const items = await this.getPracticeItems(organizationId, [practice.id]); const documents = await this.listPracticeDocuments(organizationId, practice.id); return { ...summary, items: items.get(practice.id) ?? [], documents }; }
  async getPublicPractice(publicToken: string) { const { data, error } = await this.supabase.from("practices").select().eq("public_token", publicToken).eq("public_link_enabled", true).maybeSingle(); throwIfError(error, "Failed to get public practice"); if (!data) return null; const practice = mapPractice(data); const { data: org, error: orgError } = await this.supabase.from("organizations").select().eq("id", practice.organizationId).maybeSingle(); throwIfError(orgError, "Failed to get organization"); const detail = await this.getPracticeDetail(practice.organizationId, practice.id); if (!detail || !org) return null; return { ...detail, organization: mapOrganization(org), canUpload: practice.status !== "archived" }; }
  async logPublicLinkOpened(publicToken: string) { const portal = await this.getPublicPractice(publicToken); if (portal) await this.createActivityLogEvent({ organizationId: portal.practice.organizationId, practiceId: portal.practice.id, practiceItemId: null, documentId: null, eventType: "public_link_opened", actorType: "client", metadata: {} }); }
  async updatePracticeStatus(organizationId: ID, practiceId: ID, status: PracticeStatus) { const { data, error } = await this.supabase.from("practices").update({ status, archived_at: status === "archived" ? now() : null }).eq("organization_id", organizationId).eq("id", practiceId).select().maybeSingle(); throwIfError(error, "Failed to update practice status"); return mapPractice(requireData(data, "Practice not found.")); }
  async updatePracticeItem(organizationId: ID, practiceItemId: ID, input: { status: PracticeItemStatus; required: boolean; note?: string | null }) { const timestamp = now(); const { data, error } = await this.supabase.from("practice_items").update({ status: input.status, required: input.required, note: normalizeText(input.note), updated_at: timestamp }).eq("organization_id", organizationId).eq("id", practiceItemId).select().maybeSingle(); throwIfError(error, "Failed to update practice item"); const item = mapPracticeItem(requireData(data, "Practice item not found.")); throwIfError((await this.supabase.from("practices").update({ updated_at: timestamp }).eq("organization_id", organizationId).eq("id", item.practiceId)).error, "Failed to touch parent practice"); return item; }
  async setPracticePublicLinkEnabled(organizationId: ID, practiceId: ID, enabled: boolean) { const { data, error } = await this.supabase.from("practices").update({ public_link_enabled: enabled }).eq("organization_id", organizationId).eq("id", practiceId).select().maybeSingle(); throwIfError(error, "Failed to update public link"); const practice = mapPractice(requireData(data, "Practice not found.")); await this.createActivityLogEvent({ organizationId, practiceId, practiceItemId: null, documentId: null, eventType: enabled ? "public_link_enabled" : "public_link_disabled", actorType: "studio", metadata: {} }); return practice; }
  async uploadClientDocument(publicToken: string, practiceItemId: ID, file: Parameters<StudioRepository["uploadClientDocument"]>[2]) { validateUploadFile(file); const portal = await this.getPublicPractice(publicToken); if (!portal) throw new Error("Link non valido o disabilitato."); if (!portal.canUpload) throw new Error("Questa pratica e archiviata e non accetta nuovi caricamenti."); const item = portal.items.find((i) => i.id === practiceItemId); if (!item) throw new Error("Documento non trovato per questa pratica."); if (item.status === "approved" || item.status === "not_needed") throw new Error("Questo documento e gia completato."); assertCanAddFileToPracticeItem(portal.documents.filter((d) => d.practiceItemId === practiceItemId && d.status === "active").length); const documentId = createId(); const safeFileName = sanitizeFileName(file.name); const storedFileName = `${documentId}-${safeFileName}`; const storagePath = `org-${portal.practice.organizationId}/practice-${portal.practice.id}/item-${practiceItemId}/${storedFileName}`; await this.storage.upload({ bucket: env.storageBucket, path: storagePath, file: await file.arrayBuffer(), contentType: file.type }); const { data, error } = await this.supabase.from("document_records").insert({ id: documentId, organization_id: portal.practice.organizationId, client_id: portal.practice.clientId, practice_id: portal.practice.id, practice_item_id: practiceItemId, request_id: null, storage_path: storagePath, file_name: file.name, content_type: file.type, size_bytes: file.size, original_file_name: file.name, stored_file_name: storedFileName, mime_type: file.type, file_size_bytes: file.size, uploaded_by_type: "client", status: "active" }).select().single(); if (error) { await this.storage.remove(env.storageBucket, [storagePath]); throw new Error(`Failed to create document record: ${error.message}`); } const document = mapDocument(requireData(data, "Document was not returned.")); throwIfError((await this.supabase.from("practice_items").update({ status: "uploaded" }).eq("organization_id", portal.practice.organizationId).eq("practice_id", portal.practice.id).eq("id", practiceItemId)).error, "Failed to update practice item"); await this.refreshPracticeStatus(portal.practice.organizationId, portal.practice.id); await this.createActivityLogEvent({ organizationId: portal.practice.organizationId, practiceId: portal.practice.id, practiceItemId, documentId: document.id, eventType: "document_uploaded", actorType: "client", metadata: { mimeType: file.type, fileSizeBytes: file.size } }); return document; }
  async listPracticeDocuments(organizationId: ID, practiceId: ID) { const { data, error } = await this.supabase.from("document_records").select().eq("organization_id", organizationId).eq("practice_id", practiceId).eq("status", "active").order("created_at", { ascending: false }); throwIfError(error, "Failed to list documents"); return (data ?? []).map(mapDocument); }
  async createDocumentSignedUrl(organizationId: ID, documentId: ID) { const { data, error } = await this.supabase.from("document_records").select().eq("organization_id", organizationId).eq("id", documentId).eq("status", "active").maybeSingle(); throwIfError(error, "Failed to get document"); const document = mapDocument(requireData(data, "Document not found.")); return this.storage.createSignedUrl(env.storageBucket, document.storagePath, 600); }
  async deleteDocument(organizationId: ID, documentId: ID) { const { data, error } = await this.supabase.from("document_records").update({ status: "deleted" }).eq("organization_id", organizationId).eq("id", documentId).select().maybeSingle(); throwIfError(error, "Failed to delete document"); const document = mapDocument(requireData(data, "Document not found.")); await this.storage.remove(env.storageBucket, [document.storagePath]); await this.createActivityLogEvent({ organizationId, practiceId: document.practiceId, practiceItemId: document.practiceItemId, documentId: document.id, eventType: "document_deleted", actorType: "studio", metadata: {} }); }
  async getDashboard(organizationId: ID): Promise<StudioDashboard> { const practices = await this.listPractices(organizationId); return { totalPractices: practices.length, inProgress: practices.filter((s) => s.practice.status === "in_progress").length, needsReview: practices.filter((s) => s.practice.status === "needs_review").length, complete: practices.filter((s) => s.practice.status === "complete").length, totalMissingDocuments: practices.reduce((t, s) => t + s.missingItemCount, 0), recentPractices: practices.slice(0, 5) }; }
  private async getDefault730Template() { const { data: templateRow, error } = await this.supabase.from("checklist_templates").select().eq("key", DEFAULT_730_TEMPLATE_KEY).eq("is_default", true).is("organization_id", null).maybeSingle(); throwIfError(error, "Failed to get template"); if (!templateRow) return null; const template = mapTemplate(templateRow); const { data: cats, error: catError } = await this.supabase.from("checklist_template_categories").select().eq("template_id", template.id).order("sort_order", { ascending: true }); throwIfError(catError, "Failed to get categories"); const { data: items, error: itemError } = await this.supabase.from("checklist_template_items").select().eq("template_id", template.id).order("sort_order", { ascending: true }); throwIfError(itemError, "Failed to get items"); return { template, categories: (cats ?? []).map(mapCategory), items: (items ?? []).map(mapTemplateItem) }; }
  private async toPracticeSummaries(organizationId: ID, practices: Practice[]) { if (practices.length === 0) return []; const clientIds = [...new Set(practices.map((p) => p.clientId))]; const { data, error } = await this.supabase.from("client_profiles").select().eq("organization_id", organizationId).in("id", clientIds); throwIfError(error, "Failed to list clients"); const clients = new Map((data ?? []).map((r) => [r.id, mapClient(r)])); const itemsByPracticeId = await this.getPracticeItems(organizationId, practices.map((p) => p.id)); return practices.map((practice) => { const client = clients.get(practice.clientId); if (!client) return null; const items = itemsByPracticeId.get(practice.id) ?? []; return { practice, client, progress: calculatePracticeProgress(items), missingItemCount: countMissingRequiredItems(items) }; }).filter((s): s is PracticeSummary => s !== null); }
  private async toPracticeSummary(organizationId: ID, practice: Practice) { const [summary] = await this.toPracticeSummaries(organizationId, [practice]); return summary ?? null; }
  private async getPracticeItems(organizationId: ID, practiceIds: ID[]) { if (practiceIds.length === 0) return new Map<ID, PracticeItem[]>(); const { data, error } = await this.supabase.from("practice_items").select().eq("organization_id", organizationId).in("practice_id", practiceIds).order("sort_order", { ascending: true }); throwIfError(error, "Failed to get items"); return (data ?? []).map(mapPracticeItem).reduce((groups, item) => { const existing = groups.get(item.practiceId) ?? []; existing.push(item); groups.set(item.practiceId, existing); return groups; }, new Map<ID, PracticeItem[]>()); }
  private async refreshPracticeStatus(organizationId: ID, practiceId: ID) { const detail = await this.getPracticeDetail(organizationId, practiceId); if (!detail || detail.practice.status === "archived") return; const status = deriveSuggestedPracticeStatus(detail.practice, detail.items); throwIfError((await this.supabase.from("practices").update({ status }).eq("organization_id", organizationId).eq("id", practiceId)).error, "Failed to refresh status"); }
  private async createActivityLogEvent(input: { organizationId: ID; practiceId: ID | null; practiceItemId: ID | null; documentId: ID | null; eventType: Database["public"]["Enums"]["activity_event_type"]; actorType: Database["public"]["Enums"]["activity_actor_type"]; metadata: Record<string, unknown> }) { const { error } = await this.supabase.from("activity_log_events").insert({ organization_id: input.organizationId, practice_id: input.practiceId, practice_item_id: input.practiceItemId, document_id: input.documentId, event_type: input.eventType, actor_type: input.actorType, metadata: input.metadata as Database["public"]["Tables"]["activity_log_events"]["Insert"]["metadata"] }); throwIfError(error, "Failed to create activity event"); }
}
